// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryRelation.proto

public final class QueryRelation {
  private QueryRelation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RelationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string sourceGuid = 1;
    /**
     * <code>optional string sourceGuid = 1;</code>
     */
    boolean hasSourceGuid();
    /**
     * <code>optional string sourceGuid = 1;</code>
     */
    java.lang.String getSourceGuid();
    /**
     * <code>optional string sourceGuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getSourceGuidBytes();

    // optional string destGuid = 2;
    /**
     * <code>optional string destGuid = 2;</code>
     */
    boolean hasDestGuid();
    /**
     * <code>optional string destGuid = 2;</code>
     */
    java.lang.String getDestGuid();
    /**
     * <code>optional string destGuid = 2;</code>
     */
    com.google.protobuf.ByteString
        getDestGuidBytes();

    // optional string relType = 3;
    /**
     * <code>optional string relType = 3;</code>
     */
    boolean hasRelType();
    /**
     * <code>optional string relType = 3;</code>
     */
    java.lang.String getRelType();
    /**
     * <code>optional string relType = 3;</code>
     */
    com.google.protobuf.ByteString
        getRelTypeBytes();

    // repeated .Mention mention = 4;
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    java.util.List<QueryRelation.Mention> 
        getMentionList();
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    QueryRelation.Mention getMention(int index);
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    int getMentionCount();
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    java.util.List<? extends QueryRelation.MentionOrBuilder> 
        getMentionOrBuilderList();
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    QueryRelation.MentionOrBuilder getMentionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Relation}
   */
  public static final class Relation extends
      com.google.protobuf.GeneratedMessage
      implements RelationOrBuilder {
    // Use Relation.newBuilder() to construct.
    private Relation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Relation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Relation defaultInstance;
    public static Relation getDefaultInstance() {
      return defaultInstance;
    }

    public Relation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Relation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sourceGuid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              destGuid_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              relType_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                mention_ = new java.util.ArrayList<QueryRelation.Mention>();
                mutable_bitField0_ |= 0x00000008;
              }
              mention_.add(input.readMessage(QueryRelation.Mention.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          mention_ = java.util.Collections.unmodifiableList(mention_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueryRelation.internal_static_Relation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueryRelation.internal_static_Relation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryRelation.Relation.class, QueryRelation.Relation.Builder.class);
    }

    public static com.google.protobuf.Parser<Relation> PARSER =
        new com.google.protobuf.AbstractParser<Relation>() {
      public Relation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Relation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Relation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string sourceGuid = 1;
    public static final int SOURCEGUID_FIELD_NUMBER = 1;
    private java.lang.Object sourceGuid_;
    /**
     * <code>optional string sourceGuid = 1;</code>
     */
    public boolean hasSourceGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sourceGuid = 1;</code>
     */
    public java.lang.String getSourceGuid() {
      java.lang.Object ref = sourceGuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceGuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sourceGuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceGuidBytes() {
      java.lang.Object ref = sourceGuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string destGuid = 2;
    public static final int DESTGUID_FIELD_NUMBER = 2;
    private java.lang.Object destGuid_;
    /**
     * <code>optional string destGuid = 2;</code>
     */
    public boolean hasDestGuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string destGuid = 2;</code>
     */
    public java.lang.String getDestGuid() {
      java.lang.Object ref = destGuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destGuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destGuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestGuidBytes() {
      java.lang.Object ref = destGuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string relType = 3;
    public static final int RELTYPE_FIELD_NUMBER = 3;
    private java.lang.Object relType_;
    /**
     * <code>optional string relType = 3;</code>
     */
    public boolean hasRelType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string relType = 3;</code>
     */
    public java.lang.String getRelType() {
      java.lang.Object ref = relType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          relType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string relType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRelTypeBytes() {
      java.lang.Object ref = relType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Mention mention = 4;
    public static final int MENTION_FIELD_NUMBER = 4;
    private java.util.List<QueryRelation.Mention> mention_;
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    public java.util.List<QueryRelation.Mention> getMentionList() {
      return mention_;
    }
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    public java.util.List<? extends QueryRelation.MentionOrBuilder> 
        getMentionOrBuilderList() {
      return mention_;
    }
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    public int getMentionCount() {
      return mention_.size();
    }
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    public QueryRelation.Mention getMention(int index) {
      return mention_.get(index);
    }
    /**
     * <code>repeated .Mention mention = 4;</code>
     */
    public QueryRelation.MentionOrBuilder getMentionOrBuilder(
        int index) {
      return mention_.get(index);
    }

    private void initFields() {
      sourceGuid_ = "";
      destGuid_ = "";
      relType_ = "";
      mention_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getMentionCount(); i++) {
        if (!getMention(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSourceGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDestGuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRelTypeBytes());
      }
      for (int i = 0; i < mention_.size(); i++) {
        output.writeMessage(4, mention_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSourceGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDestGuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRelTypeBytes());
      }
      for (int i = 0; i < mention_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, mention_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QueryRelation.Relation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryRelation.Relation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryRelation.Relation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryRelation.Relation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryRelation.Relation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryRelation.Relation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QueryRelation.Relation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QueryRelation.Relation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QueryRelation.Relation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryRelation.Relation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QueryRelation.Relation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Relation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QueryRelation.RelationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueryRelation.internal_static_Relation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueryRelation.internal_static_Relation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryRelation.Relation.class, QueryRelation.Relation.Builder.class);
      }

      // Construct using QueryRelation.Relation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMentionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sourceGuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        destGuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        relType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (mentionBuilder_ == null) {
          mention_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          mentionBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueryRelation.internal_static_Relation_descriptor;
      }

      public QueryRelation.Relation getDefaultInstanceForType() {
        return QueryRelation.Relation.getDefaultInstance();
      }

      public QueryRelation.Relation build() {
        QueryRelation.Relation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QueryRelation.Relation buildPartial() {
        QueryRelation.Relation result = new QueryRelation.Relation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sourceGuid_ = sourceGuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.destGuid_ = destGuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.relType_ = relType_;
        if (mentionBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            mention_ = java.util.Collections.unmodifiableList(mention_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.mention_ = mention_;
        } else {
          result.mention_ = mentionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryRelation.Relation) {
          return mergeFrom((QueryRelation.Relation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryRelation.Relation other) {
        if (other == QueryRelation.Relation.getDefaultInstance()) return this;
        if (other.hasSourceGuid()) {
          bitField0_ |= 0x00000001;
          sourceGuid_ = other.sourceGuid_;
          onChanged();
        }
        if (other.hasDestGuid()) {
          bitField0_ |= 0x00000002;
          destGuid_ = other.destGuid_;
          onChanged();
        }
        if (other.hasRelType()) {
          bitField0_ |= 0x00000004;
          relType_ = other.relType_;
          onChanged();
        }
        if (mentionBuilder_ == null) {
          if (!other.mention_.isEmpty()) {
            if (mention_.isEmpty()) {
              mention_ = other.mention_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMentionIsMutable();
              mention_.addAll(other.mention_);
            }
            onChanged();
          }
        } else {
          if (!other.mention_.isEmpty()) {
            if (mentionBuilder_.isEmpty()) {
              mentionBuilder_.dispose();
              mentionBuilder_ = null;
              mention_ = other.mention_;
              bitField0_ = (bitField0_ & ~0x00000008);
              mentionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMentionFieldBuilder() : null;
            } else {
              mentionBuilder_.addAllMessages(other.mention_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMentionCount(); i++) {
          if (!getMention(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueryRelation.Relation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueryRelation.Relation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string sourceGuid = 1;
      private java.lang.Object sourceGuid_ = "";
      /**
       * <code>optional string sourceGuid = 1;</code>
       */
      public boolean hasSourceGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string sourceGuid = 1;</code>
       */
      public java.lang.String getSourceGuid() {
        java.lang.Object ref = sourceGuid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sourceGuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sourceGuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceGuidBytes() {
        java.lang.Object ref = sourceGuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceGuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sourceGuid = 1;</code>
       */
      public Builder setSourceGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sourceGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceGuid = 1;</code>
       */
      public Builder clearSourceGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceGuid_ = getDefaultInstance().getSourceGuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceGuid = 1;</code>
       */
      public Builder setSourceGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sourceGuid_ = value;
        onChanged();
        return this;
      }

      // optional string destGuid = 2;
      private java.lang.Object destGuid_ = "";
      /**
       * <code>optional string destGuid = 2;</code>
       */
      public boolean hasDestGuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string destGuid = 2;</code>
       */
      public java.lang.String getDestGuid() {
        java.lang.Object ref = destGuid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          destGuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destGuid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDestGuidBytes() {
        java.lang.Object ref = destGuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destGuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destGuid = 2;</code>
       */
      public Builder setDestGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        destGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destGuid = 2;</code>
       */
      public Builder clearDestGuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        destGuid_ = getDefaultInstance().getDestGuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destGuid = 2;</code>
       */
      public Builder setDestGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        destGuid_ = value;
        onChanged();
        return this;
      }

      // optional string relType = 3;
      private java.lang.Object relType_ = "";
      /**
       * <code>optional string relType = 3;</code>
       */
      public boolean hasRelType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string relType = 3;</code>
       */
      public java.lang.String getRelType() {
        java.lang.Object ref = relType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          relType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string relType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRelTypeBytes() {
        java.lang.Object ref = relType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          relType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string relType = 3;</code>
       */
      public Builder setRelType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        relType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string relType = 3;</code>
       */
      public Builder clearRelType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        relType_ = getDefaultInstance().getRelType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string relType = 3;</code>
       */
      public Builder setRelTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        relType_ = value;
        onChanged();
        return this;
      }

      // repeated .Mention mention = 4;
      private java.util.List<QueryRelation.Mention> mention_ =
        java.util.Collections.emptyList();
      private void ensureMentionIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          mention_ = new java.util.ArrayList<QueryRelation.Mention>(mention_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          QueryRelation.Mention, QueryRelation.Mention.Builder, QueryRelation.MentionOrBuilder> mentionBuilder_;

      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public java.util.List<QueryRelation.Mention> getMentionList() {
        if (mentionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mention_);
        } else {
          return mentionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public int getMentionCount() {
        if (mentionBuilder_ == null) {
          return mention_.size();
        } else {
          return mentionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public QueryRelation.Mention getMention(int index) {
        if (mentionBuilder_ == null) {
          return mention_.get(index);
        } else {
          return mentionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder setMention(
          int index, QueryRelation.Mention value) {
        if (mentionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMentionIsMutable();
          mention_.set(index, value);
          onChanged();
        } else {
          mentionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder setMention(
          int index, QueryRelation.Mention.Builder builderForValue) {
        if (mentionBuilder_ == null) {
          ensureMentionIsMutable();
          mention_.set(index, builderForValue.build());
          onChanged();
        } else {
          mentionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder addMention(QueryRelation.Mention value) {
        if (mentionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMentionIsMutable();
          mention_.add(value);
          onChanged();
        } else {
          mentionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder addMention(
          int index, QueryRelation.Mention value) {
        if (mentionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMentionIsMutable();
          mention_.add(index, value);
          onChanged();
        } else {
          mentionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder addMention(
          QueryRelation.Mention.Builder builderForValue) {
        if (mentionBuilder_ == null) {
          ensureMentionIsMutable();
          mention_.add(builderForValue.build());
          onChanged();
        } else {
          mentionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder addMention(
          int index, QueryRelation.Mention.Builder builderForValue) {
        if (mentionBuilder_ == null) {
          ensureMentionIsMutable();
          mention_.add(index, builderForValue.build());
          onChanged();
        } else {
          mentionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder addAllMention(
          java.lang.Iterable<? extends QueryRelation.Mention> values) {
        if (mentionBuilder_ == null) {
          ensureMentionIsMutable();
          super.addAll(values, mention_);
          onChanged();
        } else {
          mentionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder clearMention() {
        if (mentionBuilder_ == null) {
          mention_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          mentionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public Builder removeMention(int index) {
        if (mentionBuilder_ == null) {
          ensureMentionIsMutable();
          mention_.remove(index);
          onChanged();
        } else {
          mentionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public QueryRelation.Mention.Builder getMentionBuilder(
          int index) {
        return getMentionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public QueryRelation.MentionOrBuilder getMentionOrBuilder(
          int index) {
        if (mentionBuilder_ == null) {
          return mention_.get(index);  } else {
          return mentionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public java.util.List<? extends QueryRelation.MentionOrBuilder> 
           getMentionOrBuilderList() {
        if (mentionBuilder_ != null) {
          return mentionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mention_);
        }
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public QueryRelation.Mention.Builder addMentionBuilder() {
        return getMentionFieldBuilder().addBuilder(
            QueryRelation.Mention.getDefaultInstance());
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public QueryRelation.Mention.Builder addMentionBuilder(
          int index) {
        return getMentionFieldBuilder().addBuilder(
            index, QueryRelation.Mention.getDefaultInstance());
      }
      /**
       * <code>repeated .Mention mention = 4;</code>
       */
      public java.util.List<QueryRelation.Mention.Builder> 
           getMentionBuilderList() {
        return getMentionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          QueryRelation.Mention, QueryRelation.Mention.Builder, QueryRelation.MentionOrBuilder> 
          getMentionFieldBuilder() {
        if (mentionBuilder_ == null) {
          mentionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              QueryRelation.Mention, QueryRelation.Mention.Builder, QueryRelation.MentionOrBuilder>(
                  mention_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          mention_ = null;
        }
        return mentionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Relation)
    }

    static {
      defaultInstance = new Relation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Relation)
  }

  public interface MentionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 sourceId = 1;
    /**
     * <code>optional int32 sourceId = 1;</code>
     */
    boolean hasSourceId();
    /**
     * <code>optional int32 sourceId = 1;</code>
     */
    int getSourceId();

    // optional int32 destId = 2;
    /**
     * <code>optional int32 destId = 2;</code>
     */
    boolean hasDestId();
    /**
     * <code>optional int32 destId = 2;</code>
     */
    int getDestId();

    // optional string filename = 3;
    /**
     * <code>optional string filename = 3;</code>
     */
    boolean hasFilename();
    /**
     * <code>optional string filename = 3;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>optional string filename = 3;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    // repeated string feature = 4;
    /**
     * <code>repeated string feature = 4;</code>
     */
    java.util.List<java.lang.String>
    getFeatureList();
    /**
     * <code>repeated string feature = 4;</code>
     */
    int getFeatureCount();
    /**
     * <code>repeated string feature = 4;</code>
     */
    java.lang.String getFeature(int index);
    /**
     * <code>repeated string feature = 4;</code>
     */
    com.google.protobuf.ByteString
        getFeatureBytes(int index);

    // required string sentence = 5;
    /**
     * <code>required string sentence = 5;</code>
     */
    boolean hasSentence();
    /**
     * <code>required string sentence = 5;</code>
     */
    java.lang.String getSentence();
    /**
     * <code>required string sentence = 5;</code>
     */
    com.google.protobuf.ByteString
        getSentenceBytes();
  }
  /**
   * Protobuf type {@code Mention}
   */
  public static final class Mention extends
      com.google.protobuf.GeneratedMessage
      implements MentionOrBuilder {
    // Use Mention.newBuilder() to construct.
    private Mention(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Mention(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Mention defaultInstance;
    public static Mention getDefaultInstance() {
      return defaultInstance;
    }

    public Mention getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Mention(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sourceId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              destId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              filename_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                feature_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              feature_.add(input.readBytes());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              sentence_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          feature_ = new com.google.protobuf.UnmodifiableLazyStringList(feature_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueryRelation.internal_static_Mention_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueryRelation.internal_static_Mention_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryRelation.Mention.class, QueryRelation.Mention.Builder.class);
    }

    public static com.google.protobuf.Parser<Mention> PARSER =
        new com.google.protobuf.AbstractParser<Mention>() {
      public Mention parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mention(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Mention> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 sourceId = 1;
    public static final int SOURCEID_FIELD_NUMBER = 1;
    private int sourceId_;
    /**
     * <code>optional int32 sourceId = 1;</code>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sourceId = 1;</code>
     */
    public int getSourceId() {
      return sourceId_;
    }

    // optional int32 destId = 2;
    public static final int DESTID_FIELD_NUMBER = 2;
    private int destId_;
    /**
     * <code>optional int32 destId = 2;</code>
     */
    public boolean hasDestId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 destId = 2;</code>
     */
    public int getDestId() {
      return destId_;
    }

    // optional string filename = 3;
    public static final int FILENAME_FIELD_NUMBER = 3;
    private java.lang.Object filename_;
    /**
     * <code>optional string filename = 3;</code>
     */
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string filename = 3;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filename = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string feature = 4;
    public static final int FEATURE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList feature_;
    /**
     * <code>repeated string feature = 4;</code>
     */
    public java.util.List<java.lang.String>
        getFeatureList() {
      return feature_;
    }
    /**
     * <code>repeated string feature = 4;</code>
     */
    public int getFeatureCount() {
      return feature_.size();
    }
    /**
     * <code>repeated string feature = 4;</code>
     */
    public java.lang.String getFeature(int index) {
      return feature_.get(index);
    }
    /**
     * <code>repeated string feature = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFeatureBytes(int index) {
      return feature_.getByteString(index);
    }

    // required string sentence = 5;
    public static final int SENTENCE_FIELD_NUMBER = 5;
    private java.lang.Object sentence_;
    /**
     * <code>required string sentence = 5;</code>
     */
    public boolean hasSentence() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string sentence = 5;</code>
     */
    public java.lang.String getSentence() {
      java.lang.Object ref = sentence_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sentence_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sentence = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSentenceBytes() {
      java.lang.Object ref = sentence_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sentence_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sourceId_ = 0;
      destId_ = 0;
      filename_ = "";
      feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sentence_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSentence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sourceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, destId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFilenameBytes());
      }
      for (int i = 0; i < feature_.size(); i++) {
        output.writeBytes(4, feature_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getSentenceBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sourceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, destId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFilenameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < feature_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(feature_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFeatureList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSentenceBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QueryRelation.Mention parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryRelation.Mention parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryRelation.Mention parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryRelation.Mention parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryRelation.Mention parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryRelation.Mention parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QueryRelation.Mention parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QueryRelation.Mention parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QueryRelation.Mention parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryRelation.Mention parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QueryRelation.Mention prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Mention}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QueryRelation.MentionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueryRelation.internal_static_Mention_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueryRelation.internal_static_Mention_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryRelation.Mention.class, QueryRelation.Mention.Builder.class);
      }

      // Construct using QueryRelation.Mention.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sourceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        destId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        sentence_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueryRelation.internal_static_Mention_descriptor;
      }

      public QueryRelation.Mention getDefaultInstanceForType() {
        return QueryRelation.Mention.getDefaultInstance();
      }

      public QueryRelation.Mention build() {
        QueryRelation.Mention result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QueryRelation.Mention buildPartial() {
        QueryRelation.Mention result = new QueryRelation.Mention(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sourceId_ = sourceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.destId_ = destId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.filename_ = filename_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          feature_ = new com.google.protobuf.UnmodifiableLazyStringList(
              feature_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.feature_ = feature_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sentence_ = sentence_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryRelation.Mention) {
          return mergeFrom((QueryRelation.Mention)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryRelation.Mention other) {
        if (other == QueryRelation.Mention.getDefaultInstance()) return this;
        if (other.hasSourceId()) {
          setSourceId(other.getSourceId());
        }
        if (other.hasDestId()) {
          setDestId(other.getDestId());
        }
        if (other.hasFilename()) {
          bitField0_ |= 0x00000004;
          filename_ = other.filename_;
          onChanged();
        }
        if (!other.feature_.isEmpty()) {
          if (feature_.isEmpty()) {
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFeatureIsMutable();
            feature_.addAll(other.feature_);
          }
          onChanged();
        }
        if (other.hasSentence()) {
          bitField0_ |= 0x00000010;
          sentence_ = other.sentence_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSentence()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueryRelation.Mention parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueryRelation.Mention) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 sourceId = 1;
      private int sourceId_ ;
      /**
       * <code>optional int32 sourceId = 1;</code>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sourceId = 1;</code>
       */
      public int getSourceId() {
        return sourceId_;
      }
      /**
       * <code>optional int32 sourceId = 1;</code>
       */
      public Builder setSourceId(int value) {
        bitField0_ |= 0x00000001;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sourceId = 1;</code>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 destId = 2;
      private int destId_ ;
      /**
       * <code>optional int32 destId = 2;</code>
       */
      public boolean hasDestId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 destId = 2;</code>
       */
      public int getDestId() {
        return destId_;
      }
      /**
       * <code>optional int32 destId = 2;</code>
       */
      public Builder setDestId(int value) {
        bitField0_ |= 0x00000002;
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 destId = 2;</code>
       */
      public Builder clearDestId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        destId_ = 0;
        onChanged();
        return this;
      }

      // optional string filename = 3;
      private java.lang.Object filename_ = "";
      /**
       * <code>optional string filename = 3;</code>
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000004);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        filename_ = value;
        onChanged();
        return this;
      }

      // repeated string feature = 4;
      private com.google.protobuf.LazyStringList feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFeatureIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          feature_ = new com.google.protobuf.LazyStringArrayList(feature_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public java.util.List<java.lang.String>
          getFeatureList() {
        return java.util.Collections.unmodifiableList(feature_);
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public int getFeatureCount() {
        return feature_.size();
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public java.lang.String getFeature(int index) {
        return feature_.get(index);
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFeatureBytes(int index) {
        return feature_.getByteString(index);
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public Builder setFeature(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
        feature_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public Builder addFeature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public Builder addAllFeature(
          java.lang.Iterable<java.lang.String> values) {
        ensureFeatureIsMutable();
        super.addAll(values, feature_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public Builder clearFeature() {
        feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string feature = 4;</code>
       */
      public Builder addFeatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
        return this;
      }

      // required string sentence = 5;
      private java.lang.Object sentence_ = "";
      /**
       * <code>required string sentence = 5;</code>
       */
      public boolean hasSentence() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string sentence = 5;</code>
       */
      public java.lang.String getSentence() {
        java.lang.Object ref = sentence_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sentence_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sentence = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSentenceBytes() {
        java.lang.Object ref = sentence_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sentence_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sentence = 5;</code>
       */
      public Builder setSentence(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sentence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sentence = 5;</code>
       */
      public Builder clearSentence() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sentence_ = getDefaultInstance().getSentence();
        onChanged();
        return this;
      }
      /**
       * <code>required string sentence = 5;</code>
       */
      public Builder setSentenceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sentence_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Mention)
    }

    static {
      defaultInstance = new Mention(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Mention)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Relation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Relation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Mention_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Mention_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023QueryRelation.proto\"\\\n\010Relation\022\022\n\nsou" +
      "rceGuid\030\001 \001(\t\022\020\n\010destGuid\030\002 \001(\t\022\017\n\007relTy" +
      "pe\030\003 \001(\t\022\031\n\007mention\030\004 \003(\0132\010.Mention\"`\n\007M" +
      "ention\022\020\n\010sourceId\030\001 \001(\005\022\016\n\006destId\030\002 \001(\005" +
      "\022\020\n\010filename\030\003 \001(\t\022\017\n\007feature\030\004 \003(\t\022\020\n\010s" +
      "entence\030\005 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Relation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Relation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Relation_descriptor,
              new java.lang.String[] { "SourceGuid", "DestGuid", "RelType", "Mention", });
          internal_static_Mention_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Mention_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Mention_descriptor,
              new java.lang.String[] { "SourceId", "DestId", "Filename", "Feature", "Sentence", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
